In [1]:
import pandas as  pd
from sklearn.datasets import load_svmlight_file
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from scipy.sparse import csr_matrix
import numpy as np
from scipy.sparse import hstack
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [2]:
#function for loading svmlight file 
def get_data(file):
    data = load_svmlight_file(file)
    return data[0], data[1]
#feature matrix and target vector
X, y = get_data("task_a_labeled_train.tf")

In [3]:
X
print(X)

  (0, 8)	3.0
  (0, 93)	1.0
  (0, 108)	1.0
  (0, 162)	1.0
  (0, 404)	1.0
  (0, 405)	1.0
  (0, 414)	2.0
  (0, 415)	1.0
  (0, 434)	3.0
  (0, 435)	3.0
  (0, 436)	4.0
  (0, 439)	4.0
  (0, 449)	3.0
  (0, 455)	1.0
  (0, 456)	1.0
  (0, 460)	1.0
  (0, 465)	1.0
  (0, 466)	1.0
  (0, 476)	1.0
  (0, 477)	1.0
  (0, 750)	1.0
  (0, 1014)	1.0
  (0, 1033)	14.0
  (0, 1040)	1.0
  (0, 1215)	1.0
  :	:
  (3998, 123642)	1.0
  (3998, 123643)	1.0
  (3998, 206907)	4.0
  (3999, 93)	3.0
  (3999, 103)	1.0
  (3999, 130)	1.0
  (3999, 350)	1.0
  (3999, 525)	1.0
  (3999, 587)	3.0
  (3999, 1298)	1.0
  (3999, 1299)	1.0
  (3999, 2165)	1.0
  (3999, 2558)	1.0
  (3999, 2559)	1.0
  (3999, 2675)	2.0
  (3999, 2868)	1.0
  (3999, 3410)	1.0
  (3999, 3494)	1.0
  (3999, 4205)	1.0
  (3999, 4477)	1.0
  (3999, 16949)	1.0
  (3999, 47185)	1.0
  (3999, 54546)	1.0
  (3999, 88296)	1.0
  (3999, 177402)	1.0


In [25]:
print(y)

[ 1.  1. -1. ...  1.  1.  1.]


In [26]:
#split into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2800, 206908)
(1200, 206908)
(2800,)
(1200,)


In [27]:
#fit the model
nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)

In [28]:
y_pred

array([-1., -1., -1., ...,  1.,  1., -1.])

In [36]:
# calculate accuracy of class predictions

print("Test accuracy for test data of task_a_labeled_train.tf: ",metrics.accuracy_score(y_test, y_pred)*100,"%")

Test accuracy for test data of task_a_labeled_train.tf:  96.16666666666667 %


In [30]:
#test the performance of your classifier on the data found in task_a_u00_tune.tf
X_tune, y_tune = get_data("task_a_u00_tune.tf")

In [31]:
print(X_tune)
X_tune.shape

  (0, 0)	1.0
  (0, 1)	1.0
  (0, 2)	3.0
  (0, 3)	1.0
  (0, 4)	1.0
  (0, 5)	1.0
  (0, 6)	1.0
  (0, 7)	1.0
  (0, 8)	1.0
  (0, 9)	1.0
  (0, 10)	1.0
  (0, 11)	1.0
  (0, 12)	1.0
  (0, 13)	17.0
  (0, 14)	1.0
  (0, 15)	1.0
  (0, 16)	1.0
  (0, 17)	1.0
  (0, 18)	1.0
  (0, 19)	1.0
  (0, 20)	1.0
  (0, 21)	1.0
  (0, 22)	1.0
  (0, 23)	1.0
  (0, 24)	1.0
  :	:
  (2499, 4122)	1.0
  (2499, 4317)	1.0
  (2499, 4372)	1.0
  (2499, 4406)	1.0
  (2499, 4733)	1.0
  (2499, 4744)	1.0
  (2499, 6787)	1.0
  (2499, 7423)	1.0
  (2499, 7841)	1.0
  (2499, 8675)	1.0
  (2499, 10284)	3.0
  (2499, 10400)	1.0
  (2499, 11236)	1.0
  (2499, 12634)	1.0
  (2499, 15007)	1.0
  (2499, 15582)	1.0
  (2499, 19689)	1.0
  (2499, 19732)	1.0
  (2499, 21790)	1.0
  (2499, 23329)	2.0
  (2499, 27291)	1.0
  (2499, 27292)	1.0
  (2499, 44951)	1.0
  (2499, 46956)	1.0
  (2499, 48937)	1.0


(2500, 48938)

In [32]:
print(y_tune)

[-1. -1. -1. ...  1. -1. -1.]


In [33]:
#making same size for feature matrix
filler = csr_matrix((2500, 157970), dtype = np.int8)
X_tune=hstack((X_tune, filler))
X_tune.shape

(2500, 206908)

In [35]:
#test the performance of your classifier on the data found in task_a_u00_tune.tf
y_tune_predict=nb.predict(X_tune)
print("Test accuracy for test data of task_a_labeled_train.tf: ",metrics.accuracy_score(y_tune, y_tune_predict)*100,
"%")


Test accuracy for test data of task_a_labeled_train.tf:  38.76 %
